elses-eig-leg2.o : elses-mod-02.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-02.o elses-mod-01.o elses-mod-eig-leg.o elses-mod-04.o elses-mod-02.o elses-mod-03.o elses-mod-eig-leg.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o 
elses-hami-01.o : elses-mod-03.o elses-mod-03.o elses-mod-01.o elses-mod-02.o elses-mod-01.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-03.o elses-mod-01.o 
elses-kr-main.o : elses-config.o elses-mod-02.o elses-mod-04.o elses-mod-01.o 
elses-kr-setkry.o : elses-mod-04.o elses-mod-04.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o 
elses-kr-sub.o : elses-md-booking.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-03.o elses-mod-01.o elses-qm-projection-suggest.o elses-mod-04.o elses-mod-02.o elses-mod-01.o elses-mod-03.o elses-mod-01.o elses-mod-04.o elses-mod-01.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o 
elses-md-init.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-mod-03.o elses-mod-02.o elses-mod-01.o 
elses-mod-01.o : elses-lib-phys-const.o 
elses-mod-02.o : 
elses-mod-04.o : elses-mod-01.o 
elses-mod-eig-leg.o : 
elses-qm-main.o : elses-mod-03.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-03.o 
elses-xml-02.o : elses-mod-01.o elses-mod-01.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-config.o 
elses-00-main.o : elses-io-dst-write-log.o elses-lib-omp.o elses-md-dst.o elses-options.o elses-band-calc.o elses-00-version-info.o elses-md-main.o 
elses-ana-icohp.o : elses-mod-02.o elses-mod-04.o elses-md-motion.o elses-mod-03.o elses-mod-file-io.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o 
elses-ana-plot-hami.o : elses-mod-file-io.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-01.o 
elses-band-calc.o : elses-ini-load-geno.o elses-config.o elses-qm-geno.o elses-lib-wall-clock-time.o elses-qm-domain.o 
elses-config.o : 
elses-eig-leg.o : elses-mod-nrl.o elses-mod-nrl.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-03.o elses-mod-02.o elses-mod-01.o elses-mod-02.o elses-qm-domain.o elses-io-dst-write-log.o elses-la-eigen-solver.o elses-mod-eig-leg.o elses-mod-eig-leg.o elses-mod-01.o elses-mod-01.o elses-mod-01.o Nrl/nrladapt.o 
elses-eig-standard.o : elses-qm-domain.o 
elses-ext-atom-info.o : elses-qm-domain.o 
elses-ext-matrix-data.o : elses-mod-file-io.o elses-mod-02.o elses-mod-03.o elses-config.o elses-qm-domain.o 
elses-ext-test-quantum-dynamics.o : elses-ext-atom-info.o elses-ext-matrix-data.o elses-qm-domain.o 
elses-gid-basic-routines.o : elses-mod-01.o elses-mod-file-io.o elses-mod-01.o elses-gid-initial.o elses-config.o 
elses-gid-constraint.o : elses-mod-file-io.o elses-lib-read-w-comment.o elses-gid-basic-routines.o elses-config.o 
elses-gid-initial.o : elses-mod-01.o elses-qm-domain.o elses-mod-01.o elses-mod-file-io.o elses-config.o 
elses-hami-gaas-molteni.o : elses-mod-03.o elses-mod-02.o elses-mod-01.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-03.o 
elses-ini-load-common.o : elses-mod-02.o elses-mod-03.o elses-lib-math-func.o elses-ini-set-str-from-matom.o elses-ini-set-str-from-vatom.o elses-mod-04.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-md-alloc.o elses-md-velocity-routines.o elses-md-motion.o elses-mod-01.o elses-xml-sax-data-sync-matom.o elses-xml-sax-data-sync.o elses-md-dst.o elses-io-dst-system-load.o elses-xml-config.o elses-mod-01.o elses-qm-domain.o elses-config.o elses-io-dst-write-log.o 
elses-ini-load-geno.o : elses-mod-eig-leg.o elses-mod-01.o elses-qm-geno-Huckel-atom-parameters.o elses-xml-config.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-03.o elses-mod-03.o elses-mod-01.o elses-md-dst.o elses-md-save-struct.o elses-mod-01.o elses-mod-01.o elses-lib-read-w-split.o elses-gid-initial.o elses-xml-check-element-info.o elses-lib-phys-const.o elses-lib-quad-precision.o elses-xml-compat-check.o elses-md-output.o elses-qm-flexible-cutoff.o elses-lib-element-name.o elses-md-cell-change.o elses-ini-load-common.o elses-config.o elses-qm-domain.o 
elses-ini-set-str-from-matom.o : elses-mod-01.o elses-mod-01.o elses-qm-domain.o elses-config.o 
elses-ini-set-str-from-vatom.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o elses-config.o 
elses-io-ctrl-dos-plot.o : elses-mod-file-io.o elses-mod-01.o 
elses-io-ctrl-plot-eigenstates.o : elses-mod-01.o elses-mod-eig-leg.o elses-config.o elses-qm-domain.o 
elses-io-dst-system-load.o : elses-io-read-xyz-file.o elses-lib-phys-const.o elses-mod-file-io.o elses-config.o elses-qm-domain.o elses-io-dst-write-log.o 
elses-io-dst-write-log.o : elses-00-version-info.o elses-mod-file-io.o elses-config.o elses-qm-domain.o elses-lib-dst-info.o 
elses-io-pair-list-for-cohp.o : elses-mod-file-io.o elses-mod-01.o elses-qm-domain.o 
elses-io-read-xyz-file.o : elses-lib-phys-const.o elses-mod-file-io.o elses-qm-domain.o elses-io-dst-write-log.o 
elses-io-update-snapshot.o : elses-io-read-xyz-file.o elses-mod-01.o elses-io-dst-system-load.o elses-config.o elses-mod-01.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-la-eigen-solver-main.o : elses-qm-wavepacket-main.o elses-lib-mpi-wrapper-compile.o elses-config.o elses-mod-01.o elses-qm-domain.o 
elses-la-eigen-solver.o : elses-qm-domain.o 
elses-la-gkrylov-hist.o : elses-mod-03.o elses-qm-projection.o elses-config.o elses-mod-04.o elses-qm-domain.o 
elses-la-gkrylov-main-dstm.o : elses-qm-dstm-get-nna-distance.o elses-eig-standard.o elses-qm-partial-trace-dstm.o elses-la-eigen-tridiag.o elses-la-matvec-routines-dstm.o elses-lib-math-func.o elses-qm-projection.o elses-lib-wall-clock-time.o elses-la-matvec-io.o elses-mod-03.o elses-lib-phys-const.o elses-config.o elses-la-krgl-main.o elses-qm-domain.o 
elses-la-gkrylov-main.o : elses-eig-standard.o elses-lib-math-func.o elses-qm-projection.o elses-lib-wall-clock-time.o elses-la-matvec-routines.o elses-la-matvec-io.o elses-mod-03.o elses-lib-phys-const.o elses-config.o elses-qm-domain.o elses-la-krgl-main.o 
elses-la-gkrylov-output.o : elses-la-gkrylov-hist.o elses-io-ctrl-plot-eigenstates.o elses-qm-output-eigenstates.o elses-mod-eig-leg.o elses-io-ctrl-dos-plot.o elses-lib-math-func.o elses-qm-domain.o elses-mod-file-io.o elses-mod-03.o elses-mod-01.o elses-config.o elses-lib-phys-const.o elses-la-krgl-main.o 
elses-la-gscocg-cg-s-mat.o : elses-qm-projection.o 
elses-la-gscocg-main.o : elses-qm-projection.o elses-lib-wall-clock-time.o elses-la-gscocg-cg-s-mat.o elses-la-matvec-io.o elses-lib-phys-const.o 
elses-la-gscocg-tru-res.o : elses-la-matvec-io.o 
elses-la-krgl-main.o : elses-mod-03.o elses-io-ctrl-dos-plot.o elses-mod-file-io.o elses-mod-01.o elses-la-gkrylov-hist.o elses-lib-math-func.o elses-qm-projection.o elses-lib-wall-clock-time.o elses-la-matvec-routines.o elses-la-matvec-io.o elses-mod-03.o elses-lib-phys-const.o elses-config.o elses-qm-domain.o 
elses-la-matvec-dst.o : elses-qm-geno-dst.o elses-qm-dst-projection-cell.o elses-qm-domain.o 
elses-la-matvec-routines-dstm.o : elses-qm-domain.o 
elses-la-matvec-routines.o : elses-qm-projection.o elses-la-matvec-dst.o elses-qm-geno-dst.o elses-qm-domain.o 
elses-lib-mpi-wrapper-compile.o : elses-lib-dst-info.o 
elses-lib-omp.o : elses-lib-dst-info.o elses-qm-domain.o 
elses-lib-report-mpi-time.o : elses-mod-file-io.o elses-lib-mpi-wrapper-compile.o elses-lib-dst-info.o 
elses-lib-stop-signal.o : elses-mod-file-io.o elses-config.o 
elses-lib-wall-clock-time.o : 
elses-md-alloc.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-config.o 
elses-md-booking.o : elses-mod-02.o elses-mod-file-io.o elses-mod-02.o elses-mod-01.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-mod-01.o 
elses-md-cell-change.o : elses-mod-01.o elses-md-velocity-routines.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o elses-mod-03.o elses-mod-01.o elses-config.o elses-io-dst-write-log.o elses-mod-file-io.o elses-mod-01.o 
elses-md-constraint.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-file-io.o elses-mod-01.o 
elses-md-dst-booking.o : elses-qm-domain.o elses-qm-dst-projection-cell.o 
elses-md-dst-cell.o : elses-lib-dst-info.o elses-md-dst-get-atom-range.o elses-lib-mpi-wrapper-compile.o elses-mod-03.o elses-md-dst.o elses-lib-phys-const.o elses-config.o elses-qm-domain.o 
elses-md-dst-get-atom-range.o : elses-md-dst.o elses-lib-dst-info.o elses-qm-domain.o 
elses-md-dst-update-cell-booking.o : elses-md-dst-get-atom-range.o elses-lib-mpi-wrapper-compile.o elses-md-dst.o elses-md-dst-cell.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-md-dst.o : elses-lib-mpi-wrapper-compile.o elses-config.o elses-00-version-info.o elses-lib-dst-info.o elses-qm-domain.o 
elses-md-get-distance.o : elses-qm-domain.o 
elses-md-main.o : elses-qm-geno-output.o elses-qm-output-matrices.o elses-lib-report-mpi-time.o elses-lib-stop-signal.o elses-lib-mpi-wrapper-compile.o elses-md-dst.o elses-lib-dst-info.o elses-qm-engine-dst.o elses-ini-load-geno.o elses-qm-engine.o elses-lib-wall-clock-time.o elses-md-output.o elses-md-save-struct.o elses-md-motion-verlet.o elses-md-motion.o elses-mod-03.o elses-config.o elses-mod-01.o 
elses-md-make-bk-list-w-cell.o : elses-md-dst-get-atom-range.o elses-lib-mpi-wrapper-compile.o elses-md-get-distance.o elses-md-dst-cell.o elses-md-dst.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-md-motion-verlet.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-md-velocity-routines.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-config.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-md-motion.o : elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-lib-phys-const.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-gid-constraint.o elses-io-update-snapshot.o elses-lib-mpi-wrapper-compile.o elses-qm-population.o elses-md-motion-verlet.o elses-md-constraint.o elses-md-cell-change.o elses-md-velocity-routines.o elses-mod-01.o elses-config.o elses-io-dst-write-log.o elses-mod-01.o 
elses-md-output-atom-energy.o : elses-mod-01.o elses-mod-file-io.o elses-md-velocity-routines.o elses-qm-geno.o elses-qm-geno-output.o elses-mod-01.o elses-config.o elses-qm-domain.o 
elses-md-output.o : elses-md-velocity-routines.o elses-mod-01.o elses-mod-01.o elses-md-motion.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-mod-01.o elses-md-virial-pressure.o elses-lib-mpi-wrapper-compile.o elses-mod-file-io.o elses-qm-domain.o elses-md-output-atom-energy.o elses-qm-output-atom-charge.o elses-config.o elses-lib-dst-info.o elses-00-version-info.o elses-mod-01.o 
elses-md-save-restart-xml.o : elses-md-dst-get-atom-range.o elses-qm-domain.o elses-config.o elses-mod-file-io.o elses-mod-01.o elses-config.o elses-md-dst.o elses-io-dst-write-log.o elses-mod-01.o 
elses-md-save-struct.o : elses-mod-01.o elses-config.o elses-mod-01.o elses-mod-file-io.o elses-mod-01.o elses-qm-domain.o elses-lib-dst-info.o elses-md-save-restart-xml.o elses-mod-01.o elses-config.o elses-io-dst-write-log.o 
elses-md-velocity-routines.o : elses-lib-random-num.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o elses-config.o 
elses-md-virial-pressure.o : elses-md-velocity-routines.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-lib-phys-const.o elses-config.o 
elses-mod-03.o : elses-config.o 
elses-mod-nrl.o : elses-config.o 
elses-options.o : elses-config.o 
elses-qm-alloc-charge.o : elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-charge-from-weight-dst.o : elses-lib-mpi-wrapper-compile.o elses-lib-math-func.o elses-md-dst.o elses-lib-phys-const.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-chk-allocated.o : elses-mod-04.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o elses-config.o 
elses-qm-cohp-dstm-plot.o : elses-lib-phys-const.o elses-mod-01.o elses-config.o elses-mod-file-io.o elses-md-dst.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-cohp-dstm.o : elses-qm-cohp-dstm-plot.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-domain.o : elses-mod-eig-leg.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-config.o elses-mod-01.o elses-mod-nrl.o elses-mod-03.o elses-mod-nrl.o elses-mod-03.o elses-mod-01.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-mod-02.o elses-mod-03.o elses-mod-02.o elses-mod-03.o elses-mod-01.o 
elses-qm-dst-dens-mat.o : elses-mod-01.o elses-md-dst.o elses-mod-01.o elses-qm-geno-dst.o elses-qm-dst-projection-cell.o elses-qm-domain.o 
elses-qm-dst-domain.o : elses-qm-projection-list-dstm.o elses-mod-03.o elses-mod-04.o elses-mod-04.o elses-ini-set-str-from-vatom.o elses-qm-dstm-ini-setting.o elses-md-dst-update-cell-booking.o elses-md-dst-cell.o elses-mod-01.o elses-mod-01.o elses-config.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-dst-global-dens-mat.o : elses-la-krgl-main.o elses-mod-03.o elses-lib-mpi-wrapper-compile.o elses-qm-domain.o 
elses-qm-dst-global-ham-mat.o : elses-mod-01.o elses-lib-mpi-wrapper-compile.o elses-md-dst.o elses-qm-dst-projection-cell.o elses-qm-geno-dst.o elses-qm-domain.o 
elses-qm-dst-global-weight.o : elses-config.o elses-lib-mpi-wrapper-compile.o elses-qm-domain.o elses-la-krgl-main.o 
elses-qm-dst-micro-mat.o : elses-qm-geno-Huckel.o elses-md-get-distance.o elses-mod-03.o elses-qm-domain.o 
elses-qm-dst-projection-cell.o : elses-mod-02.o elses-qm-projection-suggest.o elses-md-dst-get-atom-range.o elses-qm-dst-domain.o elses-mod-04.o elses-md-dst.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-dstm-get-nna-distance.o : elses-md-get-distance.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-dstm-ini-setting.o : elses-qm-alloc-charge.o elses-md-make-bk-list-w-cell.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-03.o elses-config.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-engine-csc-tb0.o : elses-qm-geno.o elses-qm-solver-geno-main.o elses-config.o elses-qm-domain.o 
elses-qm-engine-csc.o : elses-qm-geno-csc-basic.o elses-qm-geno-output.o elses-qm-geno-csc.o elses-qm-geno.o elses-qm-solver-geno-main.o elses-lib-phys-const.o elses-config.o elses-qm-domain.o 
elses-qm-engine-dst.o : elses-mod-01.o elses-mod-02.o elses-qm-cohp-dstm-plot.o elses-lib-wall-clock-time.o elses-qm-geno-csc-dst.o elses-md-dst.o elses-qm-dst-domain.o elses-qm-solver-gkrylov-dst.o elses-md-velocity-routines.o elses-qm-engine-csc-tb0.o elses-qm-engine-csc.o elses-qm-engine-nrl.o elses-qm-nrl.o elses-qm-geno-output.o elses-qm-geno-csc.o elses-qm-geno.o elses-qm-solver-geno-main.o elses-config.o elses-mod-02.o elses-mod-01.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-engine-nrl.o : elses-qm-output-matrices.o elses-qm-nrl.o elses-qm-geno-output.o elses-qm-solver-geno-main.o elses-config.o elses-mod-01.o elses-qm-domain.o 
elses-qm-engine.o : elses-ext-test-quantum-dynamics.o elses-qm-output-eigenstates.o elses-qm-output-matrices.o elses-qm-output-icohp.o elses-qm-population-ortho.o elses-qm-set-s-as-i.o elses-qm-population.o elses-md-velocity-routines.o elses-qm-engine-csc-tb0.o elses-qm-engine-csc.o elses-qm-engine-nrl.o elses-qm-nrl.o elses-qm-geno-output.o elses-qm-geno-csc.o elses-qm-geno.o elses-qm-solver-geno-main.o elses-config.o elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-qm-domain.o 
elses-qm-flexible-cutoff.o : elses-config.o 
elses-qm-geno-Huckel-atom-parameters.o : elses-mod-file-io.o elses-lib-dst-info.o elses-lib-sort.o elses-qm-vdW-parameters.o elses-xml-misc.o elses-config.o elses-mod-01.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-geno-Huckel.o : elses-config.o Nrl/skderiv.o Nrl/sktable.o elses-mod-01.o elses-qm-geno-Huckel-atom-parameters.o elses-qm-domain.o 
elses-qm-geno-csc-basic.o : elses-mod-file-io.o elses-qm-geno-Huckel-atom-parameters.o elses-mod-01.o elses-config.o 
elses-qm-geno-csc-dst.o : elses-mod-01.o elses-lib-mpi-wrapper-compile.o elses-qm-geno-dst.o elses-mod-02.o elses-qm-dst-projection-cell.o elses-qm-geno-csc.o elses-qm-geno-Huckel-atom-parameters.o elses-qm-domain.o 
elses-qm-geno-csc.o : elses-mod-01.o elses-qm-geno-Huckel-atom-parameters.o elses-qm-domain.o 
elses-qm-geno-dst.o : elses-mod-02.o elses-qm-dst-projection-cell.o elses-qm-geno-Huckel.o elses-qm-domain.o 
elses-qm-geno-output.o : elses-lib-phys-const.o elses-qm-output-participation.o elses-mod-01.o elses-qm-output-icohp.o elses-qm-output-eigenstates.o elses-io-ctrl-plot-eigenstates.o elses-mod-02.o elses-qm-solver-eig-geno.o elses-config.o elses-qm-domain.o 
elses-qm-geno-rest-dstm.o : elses-qm-geno-rest-kernal.o elses-md-get-distance.o elses-qm-geno-Huckel.o elses-config.o elses-qm-domain.o 
elses-qm-geno-rest-kernal.o : elses-md-get-distance.o elses-qm-geno-Huckel.o elses-qm-domain.o 
elses-qm-geno.o : elses-qm-geno-rest-kernal.o elses-mod-01.o elses-mod-02.o elses-mod-file-io.o elses-lib-sort.o elses-lib-wall-clock-time.o elses-qm-geno-Huckel.o elses-config.o elses-qm-geno-Huckel-atom-parameters.o elses-qm-domain.o 
elses-qm-nrl.o : elses-mod-01.o elses-mod-02.o elses-mod-file-io.o elses-mod-01.o elses-mod-nrl.o elses-mod-03.o elses-mod-02.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-nrl.o elses-mod-03.o elses-mod-03.o elses-mod-03.o elses-mod-01.o Nrl/nrladapt.o elses-mod-02.o elses-mod-nrl.o elses-config.o elses-mod-01.o 
elses-qm-output-atom-charge-ortho.o : elses-config.o elses-qm-domain.o 
elses-qm-output-atom-charge.o : elses-mod-01.o elses-mod-file-io.o elses-qm-geno-output.o elses-config.o elses-qm-geno-Huckel-atom-parameters.o elses-mod-01.o elses-qm-domain.o 
elses-qm-output-eigenstates.o : elses-mod-eig-leg.o elses-qm-geno-Huckel-atom-parameters.o elses-md-save-struct.o elses-mod-03.o elses-mod-file-io.o elses-config.o elses-qm-domain.o 
elses-qm-output-icohp.o : elses-qm-output-rest-energy-pair.o elses-qm-geno.o elses-mod-01.o elses-config.o elses-mod-02.o elses-qm-domain.o elses-lib-phys-const.o elses-mod-file-io.o 
elses-qm-output-levels.o : elses-qm-output-participation.o elses-mod-file-io.o elses-mod-eig-leg.o elses-config.o elses-qm-domain.o 
elses-qm-output-matrices.o : elses-mod-file-io.o elses-mod-02.o elses-mod-03.o elses-qm-domain.o elses-mod-01.o elses-qm-output-levels.o elses-config.o elses-lib-phys-const.o 
elses-qm-output-participation.o : elses-mod-file-io.o elses-mod-03.o elses-mod-eig-leg.o elses-mod-01.o elses-qm-domain.o 
elses-qm-output-rest-energy-pair.o : elses-md-get-distance.o elses-qm-geno-Huckel.o elses-mod-01.o elses-config.o elses-mod-02.o elses-lib-phys-const.o elses-mod-file-io.o elses-qm-domain.o 
elses-qm-partial-trace-dstm.o : elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-population-ortho.o : elses-config.o elses-config.o elses-lib-dst-info.o elses-qm-domain.o 
elses-qm-population.o : elses-qm-geno.o elses-config.o elses-config.o elses-lib-dst-info.o elses-qm-domain.o 
elses-qm-projection-list-dstm.o : elses-mod-file-io.o elses-lib-wall-clock-time.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-projection-suggest.o : elses-mod-04.o elses-lib-phys-const.o elses-mod-03.o elses-config.o elses-qm-domain.o elses-io-dst-write-log.o 
elses-qm-projection.o : elses-mod-03.o elses-qm-domain.o elses-mod-01.o elses-mod-02.o elses-mod-04.o elses-lib-wall-clock-time.o elses-mod-01.o 
elses-qm-set-s-as-i.o : elses-qm-domain.o elses-config.o 
elses-qm-solver-eig-geno.o : elses-io-pair-list-for-cohp.o elses-qm-geno.o elses-lib-math-func.o elses-lib-phys-const.o elses-io-ctrl-dos-plot.o elses-mod-file-io.o elses-lib-dst-info.o elses-la-eigen-solver-main.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-eig-leg.o elses-lib-wall-clock-time.o elses-mod-eig-leg.o elses-mod-03.o elses-config.o elses-qm-domain.o 
elses-qm-solver-geno-main.o : elses-mod-01.o elses-la-krgl-main.o elses-qm-solver-krgl.o elses-qm-solver-gscocg.o elses-qm-solver-eig-geno.o elses-config.o elses-qm-domain.o 
elses-qm-solver-gkrylov-dst.o : elses-mod-01.o elses-lib-math-func.o elses-lib-phys-const.o elses-qm-chk-allocated.o elses-qm-cohp-dstm.o elses-qm-geno-rest-dstm.o elses-qm-partial-trace-dstm.o elses-qm-charge-from-weight-dst.o elses-la-gkrylov-main-dstm.o elses-qm-dst-micro-mat.o elses-md-get-distance.o elses-lib-wall-clock-time.o elses-qm-geno-csc-dst.o elses-qm-dst-global-ham-mat.o elses-qm-geno-dst.o elses-qm-dst-domain.o elses-mod-02.o elses-mod-03.o elses-lib-mpi-wrapper-compile.o elses-qm-dst-projection-cell.o elses-la-gkrylov-main.o elses-la-gkrylov-output.o elses-mod-01.o elses-la-gkrylov-hist.o elses-qm-projection.o elses-mod-03.o elses-config.o elses-md-dst.o elses-io-dst-write-log.o elses-qm-domain.o 
elses-qm-solver-gkrylov.o : elses-mod-01.o elses-la-gkrylov-main.o elses-la-gkrylov-output.o elses-mod-01.o elses-la-gkrylov-hist.o elses-la-krgl-main.o elses-qm-projection.o elses-mod-02.o elses-qm-domain.o elses-mod-03.o elses-config.o 
elses-qm-solver-gscocg.o : elses-mod-01.o elses-la-gscocg-main.o elses-qm-projection.o elses-mod-02.o elses-qm-domain.o elses-mod-03.o 
elses-qm-solver-krgl.o : elses-mod-01.o elses-la-gkrylov-output.o elses-mod-01.o elses-la-gkrylov-hist.o elses-la-krgl-main.o elses-qm-projection.o elses-mod-02.o elses-qm-domain.o elses-mod-03.o 
elses-qm-vdW-parameters.o : elses-lib-db-covalent-radius.o elses-lib-db-polarization.o elses-lib-db-ion-ene.o elses-lib-phys-const.o elses-lib-element-name.o elses-mod-file-io.o elses-xml-get-value-with-unit.o elses-config.o 
elses-vis-main.o : elses-mod-01.o elses-mod-01.o 
elses-vis-rasmol.o : elses-mod-01.o elses-vis-main.o elses-mod-file-io.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-03.o 
elses-vis-xyz-extended.o : elses-mod-01.o elses-vis-main.o elses-mod-file-io.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-01.o elses-mod-03.o 
elses-xml-03.o : elses-mod-02.o elses-mod-01.o elses-mod-01.o elses-xml-config.o 
elses-xml-check-element-info.o : elses-qm-geno-Huckel-atom-parameters.o elses-config.o 
elses-xml-compat-check.o : elses-config.o 
elses-xml-config.o : elses-xml-sax-parser.o elses-config.o elses-xml-misc.o elses-config.o elses-config.o 
elses-xml-get-value-with-unit.o : elses-lib-phys-const.o 
elses-xml-misc.o : elses-lib-phys-const.o 
elses-xml-sax-counter.o : elses-xml-misc.o elses-config.o 
elses-xml-sax-data-sync-matom.o : elses-lib-element-name.o elses-lib-mpi-wrapper-compile.o elses-config.o 
elses-xml-sax-data-sync.o : elses-lib-element-name.o elses-lib-mpi-wrapper-compile.o elses-config.o 
elses-xml-sax-handler.o : elses-xml-misc.o elses-config.o 
elses-xml-sax-parser.o : elses-xml-sax-handler.o elses-xml-sax-counter.o elses-config.o 
Nrl/nrlvar.o : elses-mod-01.o elses-mod-02.o elses-mod-03.o elses-mod-01.o elses-mod-02.o elses-mod-02.o elses-mod-01.o elses-mod-01.o 
Nrl/nrladapt.o : elses-mod-01.o elses-mod-01.o Nrl/nrlio.o Nrl/nrlvar.o Nrl/nrlrep.o Nrl/nrlldos.o Nrl/nrlmatrix.o elses-mod-nrl.o 
Nrl/nrlhop.o : elses-xml-misc.o Nrl/nrlcut.o Nrl/nrlpair.o Nrl/nrlsystem.o Nrl/skderiv.o Nrl/sktable.o 
Nrl/nrlio.o : elses-config.o elses-xml-misc.o Nrl/nrlhop.o Nrl/nrlonsite.o Nrl/nrlmatrix.o 
Nrl/nrlmatrix.o : Nrl/nrlvar.o Nrl/nrlsystem.o Nrl/nrlhop.o Nrl/nrlonsite.o Nrl/nrlpair.o 
Nrl/nrlonsite.o : elses-xml-misc.o Nrl/nrlvar.o Nrl/nrlcut.o Nrl/nrlpair.o Nrl/nrlsystem.o 
Nrl/nrlrep.o : Nrl/nrlsystem.o 
Nrl/nrlsystem.o : Nrl/nrlvar.o 
Nrl/skderiv.o : Nrl/sktable.o 
