main.o : util/processes.o util/time.o util/distribute_matrix.o util/matrix_io.o util/command_argument.o solver/solver_main.o 
solver/solver_lapack.o : util/time.o 
solver/solver_main.o : solver/solver_scalapack_select.o solver/solver_scalapack_all.o solver/solver_lapack.o 
solver/solver_scalapack_all.o : util/distribute_matrix.o util/processes.o util/time.o 
solver/solver_scalapack_select.o : util/distribute_matrix.o util/processes.o util/time.o 
