./src/matrix_io.o : ./src/global_variables.o ./src/processes.o ./src/event_logger.o 
./src/time_evolution.o : ./src/global_variables.o ./src/event_logger.o ./src/processes.o ./src/distribute_matrix.o ./src/descriptor_parameters.o 
./src/event_logger.o : ./src/fson.o ./src/fson.o ./src/fson.o 
./src/linear_algebra.o : ./src/util.o ./src/global_variables.o ./src/processes.o ./src/event_logger.o ./src/distribute_matrix.o ./src/descriptor_parameters.o 
./src/distribute_matrix.o : ./src/processes.o ./src/matrix_io.o ./src/global_variables.o ./src/descriptor_parameters.o ./src/event_logger.o 
./src/initialization.o : ./src/util.o ./src/state.o ./src/setting.o ./src/matrix_generation.o ./src/linear_algebra.o ./src/conversion.o ./src/charge.o ./src/atom.o ./src/processes.o ./src/global_variables.o ./src/distribute_matrix.o ./src/descriptor_parameters.o 
./src/main.o : ./src/main_aux.o 
./src/atom.o : ./src/global_variables.o ./src/descriptor_parameters.o 
./src/charge.o : ./src/util.o ./src/state.o ./src/global_variables.o ./src/processes.o ./src/matrix_io.o ./src/linear_algebra.o ./src/event_logger.o ./src/descriptor_parameters.o ./src/atom.o 
./src/processes.o : ./src/global_variables.o 
./src/state.o : ./src/util.o ./src/matrix_io.o ./src/linear_algebra.o ./src/fson.o ./src/distribute_matrix.o ./src/atom.o 
./src/main_aux.o : ./src/util.o ./src/time_evolution.o ./src/state.o ./src/setting.o ./src/output.o ./src/matrix_generation.o ./src/linear_algebra.o ./src/initialization.o ./src/global_variables.o ./src/conversion.o ./src/charge.o ./src/atom.o ./src/event_logger.o ./src/fson.o ./src/fson.o ./src/fson.o ./src/fson.o ./src/processes.o ./src/distribute_matrix.o ./src/descriptor_parameters.o 
./src/fson.o : 
./src/conversion.o : ./src/state.o ./src/global_variables.o ./src/processes.o ./src/linear_algebra.o ./src/distribute_matrix.o ./src/descriptor_parameters.o 
./src/setting.o : ./src/global_variables.o ./src/fson.o ./src/fson.o ./src/fson.o 
./src/matrix_generation.o : ./src/util.o ./src/state.o ./src/linear_algebra.o ./src/global_variables.o ./src/conversion.o ./src/processes.o ./src/stats.o ./src/event_logger.o ./src/distribute_matrix.o ./src/descriptor_parameters.o ./src/charge.o ./src/atom.o 
./src/output.o : ./src/util.o ./src/state.o ./src/setting.o ./src/linear_algebra.o ./src/global_variables.o ./src/processes.o ./src/event_logger.o ./src/fson.o ./src/fson.o ./src/fson.o ./src/descriptor_parameters.o ./src/charge.o ./src/atom.o 
